Setup
Theophileaseh/React-To-Do pull request #1
Opened 2022-05-30 07:32 UTC by Theophileaseh

Update created To-Do List App using React

2022-05-30 18:26 UTC, white3d commented
Hi @Theophileaseh,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Highlights

Invalid Code Review Request
Required Changes ♻️

- [ ] You have submitted a project that has failed to pass linters check. Kindly remove all the linters errors in the code and resubmit.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

2022-06-04 08:34 UTC, christianbiring1 requested changes
Hi @Theophileaseh;
## Good job so far!
![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/171990964-92cd9ae4-2a53-4afa-b452-b1bcae1568b0.gif)

Here are some highlights of your project:

- [ ] The project works perfectly,
- [ ]  Gitflow was correctly used
> - Components
> - Props and state usage
> - Events
> - Lifting state up
> - Hooks
    


Were perfectly used.

However, there is still something you have to rectify so that you can take your project to the next level :rocket: 
- [ ] Consider using a descriptive title for your PR `telling what changes are inside`
- [ ] Pull request should have a short summary describing introduced changes in more detail.
- [ ] The lint result should be **`green`**! consider fixing them.

Cheers and Happy coding!   :clap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-06-04 08:34 UTC, christianbiring1 commented on README.md
> +> React To Do is a to-do list app built using react framework.
- [ ] Consider not removing the title of each point of your `README` to make obvious to the reader what she/he mighty be reading. in this case `Project Description`
- [ ] It would be okay to be more detailed in your `description`. `What the App is for?`

2022-06-04 08:34 UTC, christianbiring1 commented on README.md
> +- Technologies used: Webpack, big-js, babel
Consider not mentioning the tools that weren't used in the project. in this case `big-js`
It's a third part that enables JavaScript to deal with big numbers. `eg: 1235678909000000875654353`

2023-03-20 13:40 UTC, merged